---
language: python
python:
  - "3.8"

sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - platformio update

before_script:
  - cp desk-station/src/secrets-example.h desk-station/src/secrets.h

script:
  - ( cd arduino-epd && platformio run )
  - ( cd circuit-playground && platformio run )
  - ( cd desk-station && platformio run )
